### ISSUE TITLE
Undefined offset: simple-social-icons.php:405

### ISSUE THREAD

**Issue by ctalkington** [copyblogger/simple-social-icons#12]
with WP_DEBUG on it looks like the code to build css creates a notice when no instances are setup.

``` php
$instance = wp_parse_args( $all_instances[$this->number], $this->defaults );
```

**Comment by rrennick** [comment]
@nathanrice this one is ready for testing.

**Comment by bgardner** [comment]
@rrennick Better late than never. Do you think this code is still good based on the 2.0 update the plugin recently was given?

cc: @dreamwhisper @nathanrice

**Comment by rrennick** [comment]
It looks like it's already there - https://github.com/copyblogger/simple-social-icons/blob/develop/simple-social-icons.php#L419

**Comment by bgardner** [comment]
So it's in there already, and we can close this issue?

**Comment by rrennick** [comment]
Yes & closing.
