### ISSUE TITLE
Icon requests: Slideshare, Medium, Goodreads, TripAdvisor, iTunes

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/simple-social-icons#13]
A user on WP.org made [this request](https://wordpress.org/support/topic/please-add-icon-for-slideshare?replies=1#post-6982448):

> Please, please add an icon for SlideShare. We work with a lot of academic people and this would be lovely to have! I know it's silly because I could just add icons without the plugin, but I love this plugin (thank you!), it saves so much time.

The icon's available from Entypo+ and Font Awesome via icomoon:

![icomoon_app_-_icon_font__svg__pdf___png_generator](https://cloud.githubusercontent.com/assets/647669/7779161/0426796e-00ca-11e5-915f-235c817466c9.jpg)

**Comment by bgardner** [comment]
Related, per conversation with @rafaltomal yesterday.

Icon for Medium.

**Comment by nickcernis** [comment]
Two votes here for a Goodreads icon (to be used with our new Author Pro theme): https://wordpress.org/support/topic/goodreads-icon?replies=2#post-7072583

I couldn't find a Goodreads icon on icomoon, but it's possible we could add our own version to the kit.

**Comment by chuckreynolds** [comment]
Came here to suggest SnapChat. fwiw. +1
