### ISSUE TITLE
Update Google+ icon

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/simple-social-icons#17]
Google and Google+ rebranded recently: https://developers.google.com/+/branding-guidelines?hl=en

![g _signin_short](https://cloud.githubusercontent.com/assets/647669/9795772/8435be68-57ea-11e5-85bc-a2e471d2d8e9.png)

Font Awesome and other icon fonts haven't updated to include the new icon yet, but we may need to swap out our version of it when they do.

https://github.com/FortAwesome/Font-Awesome/issues/7357

**Comment by tomnunn** [comment]
Font Awesome have since updated to the New Google Plus Icon.

**Comment by bgardner** [comment]
Closing via https://github.com/copyblogger/simple-social-icons/commit/9a6e92242643f2834f026eee2321967503e208b1
