### ISSUE TITLE
Consider changing the default styles filter for v2.0?

### ISSUE THREAD

**Issue by robincornett** [copyblogger/simple-social-icons#30]
With the significant changes to the markup, beyond just the change to using SVG, themes which have used the `simple_social_default_css` filter to override the plugin stylesheet will experience significant styling issues.

Since the `simple_social_default_glyphs` filter is being removed/replaced in 2.0, I'd like to suggest that the stylesheet filter be treated similarly. Although it may cause some minor styling issues, I think it would be a lot less destructive than leaving it in, for those who have used it. Simply changing the filter hook name seems like it should be sufficient.

**Comment by mjsdiaz** [comment]
I would also like to see the simple_social_default_css filter changed, as Robin recommends.

**Comment by bgardner** [comment]
Assigning to @laurenmancke and wanted to get feedback from @dreamwhisper from a support perspective.

**Comment by robincornett** [comment]
Here's a visual example of 2.0 with a theme using the default glyphs and default styles filters:
![image](https://cloud.githubusercontent.com/assets/4853066/20802066/cf6e295e-b7b8-11e6-9de9-38b4fc2f82af.png)
Since the glyphs are deprecated, it's using the new SVGs and all markup, but the old CSS, which obviously does bad things. Tweaking the filter hook name resolves everything.

Thank you for looking into this--much appreciated.

**Comment by dreamwhisper** [comment]
@bgardner I would agree with @robincornett that we should rename the filter.

**Comment by bgardner** [comment]
Go with something like simple_social_default_css_deprecated?

**Comment by robincornett** [comment]
Why not `simple_social_default_stylesheet`, since it's still available if someone wants to use it in 2.0? And it is modifying a stylesheet URL?

**Comment by bgardner** [comment]
I'm good with that. cc: @laurenmancke

**Comment by bgardner** [comment]
Actually, @robincornett if you were up for issuing a PR on this, we can have @nathanrice merge it. This way I have the pleasure of adding you to the props section when I update the StudioPress post.  ;-)

**Comment by bgardner** [comment]
Or I can.  :-P
