### ISSUE TITLE
Icons stretched in 2.0.0 in Genesis Design Pro

### ISSUE THREAD

**Issue by nformbiz** [copyblogger/simple-social-icons#39]
Attached is the output in Genesis Design Pro after upgrading to 2.0.0.  Everything goes back to normal when I downgrade to PR32.
![2016-12-07_12-51-03](https://cloud.githubusercontent.com/assets/24426343/20955814/01bbede8-bc81-11e6-845d-878dbf9837ad.jpg)
Kind regards,
Mike

**Comment by bgardner** [comment]
My guess is that this has something to do with CSS caching more than anything. Are you on Cloudflare? Also a link to this would also be very helpful.

**Comment by nformbiz** [comment]
Hi Brian,
The issue occurred on a local install on Bitnami.  I attempted Ctrl-F5 several times.  I will be pushing the site live in a few weeks and can report then whether the issue continues with a link.  If there is something else I can show you don't hesitate to ask.
Mike

**Comment by nformbiz** [comment]
Brian,
This is resolved in 2.01
An incredible response, thanks.
Mike

**Comment by bgardner** [comment]
Awesome!  :-)

I'll close the issue...
