### ISSUE TITLE
Poor accessibility of links 

### ISSUE THREAD

**Issue by GaryJones** [copyblogger/simple-social-icons#4]
The links have very poor accessibility -  text to speech browsers simply read each one as a 'list item'  with no clue as to what it links to. 

Solutions:
- Add a title attribute to each link with the name of the site being linked to, or... 
- Make the anchor text include the name of the site being linked to, in a screen-reader-text span and style appropriately. 

Personally, I'd like to see the second option done, since that then gives the link more information for search engines or other non-style contexts.

**Comment by RRWD** [comment]
+1 for "Make the anchor text include the name of the site being linked to, in a screen-reader-text span and style appropriately.'"

**Comment by michaelbeil** [comment]
:+1:

**Comment by RRWD** [comment]
Maybe for Genesis 2.2: when the add_theme_support( 'genesis-accessibility') is true, add the site name in a span with the class screen-reader-text?

**Comment by nathanrice** [comment]
SSI has its own stylesheet we can add this to, if necessary.

**Comment by michaelbeil** [comment]
`
/* Screen Readers
------------------------------- */

.screen-reader-text,
.screen-reader-text span,
.search-form label {
	clip: rect(0, 0, 0, 0);
	height: 0;
	position: absolute;
	width: 0;
}
`

Like what you cued Robin on @RRWD.  

And then adding that class to the array:
`
'bloglovin'   => '<span class="&#xe80f;"><span class="screen-reader-text">Bloglovin</span>',
`

That could be great @nathanrice.

**Comment by GaryJones** [comment]
Here's a workaround for those who need it (hint: everybody): https://gist.github.com/robincornett/d3775b24b75e443a76e5

**Comment by nickcernis** [comment]
@GaryJones There's an upcoming update and switch to SVG that includes screenreader text spans:

- https://github.com/copyblogger/simple-social-icons/pull/28/commits/9a6e92242643f2834f026eee2321967503e208b1#diff-12a1b54f83ab74a5deb89c7b9c8cc7eeR102
- https://github.com/copyblogger/simple-social-icons/pull/28
- https://github.com/copyblogger/simple-social-icons/issues/25

**Comment by bgardner** [comment]
@nickcernis Do you think this can be closed now, due to https://github.com/copyblogger/simple-social-icons/commit/9a6e92242643f2834f026eee2321967503e208b1?

**Comment by carasmo** [comment]
In 2.0 the icons give no error but nothing at all when checked with Wave.

**Comment by GaryJones** [comment]
Since this issues was raised before 2.0, this specific implementation issue is now gone. #32 replaces it with the intention of still improving accessibility.
