### ISSUE TITLE
Fails validation when mulitple instances on page

### ISSUE THREAD

**Issue by carasmo** [copyblogger/simple-social-icons#43]
The old version didn't use IDs but this one does, so when there are multiple instances (one in the site header and one in the footer widgets) validation fails.

**Comment by bgardner** [comment]
I see your point, but as far as I know, the ID's are necessary for accessibility.

**Comment by bgardner** [comment]
Actually, each time it is used, the widget appends a -(number) afterwards. For instance, here's what I see with multiple instances on a sandbox site:

```
<section id="simple-social-icons-2" class="widget simple-social-icons">
```

And this:

```
<section id="simple-social-icons-3" class="widget simple-social-icons">
```

Unless I'm missing something here?

**Comment by bgardner** [comment]
Unless you're talking about this:

```
<title id="social-bloglovin">Bloglovin</title>
```

In which case, that ID is required for accessibility.

**Comment by bgardner** [comment]
Interesting conversation here --> https://github.com/GoogleChrome/accessibility-developer-tools/issues/210

**Comment by carasmo** [comment]
Yes, the title id is repeating. I'm using the html5 validator. I'll read the reference.

**Comment by nickcernis** [comment]
I submitted a fix for this.

@rrennick @nathanrice @bgardner If you have time to review the change, I'd be grateful for the sanity check.

**Comment by carasmo** [comment]
Yeah!

**Comment by bgardner** [comment]
Gonna keep this open until https://github.com/copyblogger/simple-social-icons/pull/45 is officially merged.
