### ISSUE TITLE
New Google Plus Icon is jaggy

### ISSUE THREAD

**Issue by carasmo** [copyblogger/simple-social-icons#46]
I don't think it's just me. The GPlus logo is not smooth. It's harder to tell when it's in a circle in white with a colored background.

![screen shot 2016-12-08 at 2 26 50 pm](https://cloud.githubusercontent.com/assets/1124594/21024452/8a55501e-bd52-11e6-8e60-35bf1261c2ad.png)

**Comment by bgardner** [comment]
@carasmo Can you provide a link to where this is happening?

**Comment by carasmo** [comment]
I set it up here with the same CSS used on my dev area

http://sandbox.christinacreativedesign.com/

**Comment by bgardner** [comment]
Hm, it looks fine to me -- as do mine as well. Are you on a Retina-display machine?  (wondering if that's the difference)

cc: @laurenmancke

**Comment by carasmo** [comment]
Strange. Not retina. All look smooth except G+ in FF and Chrome. Oh well. I'll close this.
