### ISSUE TITLE
Unclear where SVG files are stored

### ISSUE THREAD

**Issue by ryandejaegher** [copyblogger/simple-social-icons#58]
Hey I'm trying to add a new icon (Spotify) to the available list of icons. I've read the instructions but i'm not clear on how to add the SVG to the plugin. I noticed that the plugin uses Font Awesome and simply changing the class of the icon does load the Spotify icon but not with the correct styling. 

A detailed example on adding new icons including code would be great.

**Comment by nickcernis** [comment]
Hi, @ryandejaegher!

I built a working sample plugin here showing how to add icons on more detail:

https://github.com/nickcernis/ssi-custom-icons

The example adds a Spotify, Etsy, and Codepen icon, but feel free to modify it to suit you, or follow up with questions here or over there.
