### ISSUE TITLE
Facebook icon does not render on some Android devices

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/simple-social-icons#7]
Customer report:
Wordpress 3.9.1
Simple social icons plugin v1.0.6
It only has this problem when viewing with the Android Browser. (android 4.2.1 & 4.2.2).

Google chrome & Firefox for Android display the Facebook logo correctly. The latest browsers on Windows 8 work fine as well.

I've tried it on 2 Android devices, The "HP Slate 7 Plus" tablet and the original "Galaxy Nexus" phone. Both have the Facebook logo issue.

Previously reported at http://wordpress.org/support/topic/facebook-icon-f-doesnt-display-in-mobile

Replicated on Browser stack with Nexus 4/Android 4.2 using our demo
![facebook-icon](https://cloud.githubusercontent.com/assets/1271053/3856442/726fe906-1ef7-11e4-85ba-c799ba099c13.png)

**Comment by nathanrice** [comment]
@rafaltomal any idea why this would happen?

**Comment by dreamwhisper** [comment]
@nathanrice I think https://github.com/copyblogger/simple-social-icons/pull/9 fixes it

**Comment by michaelbeil** [comment]
checking on #9 locally here.

**Comment by michaelbeil** [comment]
all seems fine. i would need a few more devices to verify.
